{% set version = '1.0-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hier.part
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hier.part_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hier.part/hier.part_{{ version }}.tar.gz
  sha256: 40ea67380245f2852d1b1f8a1e36b5e85c7d898f7269aa1eaaca589dc5ba9497

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-betareg
    - r-gtools
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-betareg
    - r-gtools

test:
  commands:
    - $R -e "library('hier.part')"           # [not win]
    - "\"%R%\" -e \"library('hier.part')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=hier.part
  license: GPL-3.0-only
  summary: Partitioning of the independent and joint contributions of each variable in a multivariate
    data set, to a linear regression by hierarchical decomposition of goodness-of-fit
    measures of regressions using all subsets of predictors in the data set. (i.e.,
    model (1), (2), ..., (N), (1,2), ..., (1,N), ..., (1,2,3,...,N)). A Z-score based
    estimate of the 'importance' of each predictor is provided by using a randomisation
    test.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - slacalle

# Package: hier.part
# Type: Package
# Title: Hierarchical Partitioning
# Description: Partitioning of the independent and joint contributions of each variable in a multivariate data set, to a linear regression by hierarchical decomposition of goodness-of-fit measures of regressions using all subsets of predictors in the data set. (i.e., model (1), (2), ..., (N), (1,2), ..., (1,N), ..., (1,2,3,...,N)). A Z-score based estimate of the 'importance' of each predictor is provided by using a randomisation test.
# Version: 1.0-6
# Authors@R: c(person("Chris", "Walsh", role = c("aut","cre"), email = "cwalsh@unimelb.edu.au"), person("Ralph", "Mac Nally", role = "aut", email = "Ralph.MacNally@gmail.com"))
# Imports: gtools, betareg, MASS
# BugReports: https://github.com/cjbwalsh/hier.part/issues
# License: GPL
# Encoding: UTF-8
# LazyData: true
# NeedsCompilation: yes
# Packaged: 2020-03-03 06:18:58 UTC; cwalsh
# Author: Chris Walsh [aut, cre], Ralph Mac Nally [aut]
# Maintainer: Chris Walsh <cwalsh@unimelb.edu.au>
# Repository: CRAN
# Date/Publication: 2020-03-03 07:10:03 UTC

{% set version = '1.0-4' %}
{% set name = 'hier.part' %}

package:
  name: 'r-{{ name }}'
  version: '{{ version|replace("-", "_") }}'

source:
  url: {{ cran_mirror }}/src/contrib/{{ name }}_{{ version }}.tar.gz
  sha256: 'e9f901506b5cbbbf0539d2ed395bfd30e14ae787e109de39b8642e38ff6b4c0d'

build:
  skip: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - r-base
    - r-gtools
  run:
    - r-base
    - r-gtools

test:
  commands:
    - $R -e "library('hier.part')"

about:
  home: 'https://CRAN.R-project.org/package=hier.part'
  license: 'GPL-2,GPL-3'
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license_family: 'GPL'
  summary: 'Variance partition of a multivariate data set'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
