travis:
  secure:
    BINSTAR_TOKEN: kkI9f0O/DScH8opAR6O2AbQcriPKkVEO40hHmXhmt5imuffovJ7XnE1/rE8qTOXBWWPpeMgvNHwRrH3yYbWekewHzcOvnRajOuAMCmird1zaLTtW7lMJbPALw2JyD13mCmKTaGMlEC2cD5jwqXC0en/VMyKAqZe0oAC7qlpG6I33Slj6zXaVfkLS1dV5My6uFpSSbJ54OBFnLFTn2d3jkfY6nmXQeYmfSGis6FOmIoD7AzG9tCbGuKLlJNDQez1BQIytF2Re1bU3q7dPh4R7ggIZcVaQoJ/h8a/77NJSysvIh8lxmErzFyasXrZQMeTMBrfTiYQsqe5If0nMRn8kpxKljUSxJbru7grtdEdTgZJt+vCi7oRoWbCc5QkoRZocUVgetoFxEQbM2a3kqb11kuouaRL9qJ/L2ZhXhvi/ZyKhZ05wRjg/MMUahEbTWXJiSugCirIJuprTuA+A5xJe1iSbY6M/wwnbb3Oog8iEFKGFOYPE93pf1LBnrkjav4FH7wuhnUItYmfLL+bvV2YlVd85vXiYgDhtoV5MdyD7WoSt1AHdyH4d9+jq0Yx19lBPpz80ZvGKagKSuit9XFsBrWej7ISms5d8n/E9h8oWyRbEbfC2S4vFL+WdGX2LuospOoSwefZGV06yXE3LMy/wkA6upI47MO1zaS6DdhwBzdc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
