travis:
  secure:
    BINSTAR_TOKEN: O2F2h1XfO3L/j/5d1FILZQyzKmgrExAezH5VnHPRM/V6nvs4RHTiXcI+WzPmpb8vioe9X9Vw48BTmkOYBv4/OyNsPaJSwG34Y0UQj3NLSctB42q46tpT8jvggnPw5UFgGk9uv3ZI6hJc2f26Cmf/PN1noc4fn/9vhECP8mZxOwsgG0zjQv/IvxMj/V/nlsiimH41170qUCqP28mVVpFwB2MlZM3SfVKVWzGtROAYBKlr74P2RBY4uUocsHC0vnrbqQtSBRTYOAzFRjSvx3/YfCY/4ICt/NjjeF9+yGn8Nxf7iVwUyYNvEaI2i1x5wuRgSmc4PfQFipNaWqphWDdZBD0Vp9M2pJm5WGTIsYoJbToaxqJZjbvF+okVoIB+updl54iwpTAMmKRPK0jVcpfX9ihaqsOAB1DnLUHTjfnmb/jsJCZUAgWOBASweWbpLr/tNomPV2ZWXdpf0UaK/ZEDRZpDjJytS+u/5kUmBPOWXsbmSJCr8W2QxRvPyoyy7HQeb7scGWfxVF9dU6zchOWNOcfTtQZIpyOI2DIu9gIe+FwI3ipiYU4BcooT3oFTZNfLjbLq8opG9eTRqLd5mqYHfno1F/gN8KM7us1kdM+mGOLPBeou69G89S3vJyaUM1btbZRhH4DMFP/y9MjccOrES7AXAJBDGTFU8C2pAeBa4UE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
